const productLists = [
    {
        "id": 127766,
        "nameEnglish": "Nirbachito Probondho",
        "authorNameEnglish": "Sheikh Hasina",
        "publisherNameEnglish": "Agamee Prokashoni",
        "primaryCategoryNameEnglish": "Articles & Research Collection",
        "listPrice": 350,
        "discount": 25,
        "sellPrice": 263,
        "image": "https://ds.rokomari.store/rokomari110/ProductNew20190903/260X372/243244bb36e4_127766.jpg",
        "status": "AVAILABLE",
        "averageRating": 2.58,
        "ratingCount": 24,
        "reviewCount": 4,
        "productType": "book",
        "inStock": false,
        "productOrderType": "NORMAL",
        "quantity": 0
    },
    {
        "id": 204598,
        "nameEnglish": "Foreign Service 35 Bochor Tak Misti Jal",
        "authorNameEnglish": "ATM Nazrul Islam",
        "publisherNameEnglish": "Agamee Prokashoni",
        "primaryCategoryNameEnglish": "Workplace Memories and Experience ",
        "listPrice": 220,
        "discount": 25,
        "sellPrice": 165,
        "image": "https://ds.rokomari.store/rokomari110/ProductNew20190903/260X372/1c3a66555_204598.jpg",
        "status": "AVAILABLE",
        "averageRating": 4.6,
        "ratingCount": 5,
        "reviewCount": 3,
        "productType": "book",
        "inStock": false,
        "productOrderType": "NORMAL",
        "quantity": -2,
    },
    {
        "id": 195890,
        "nameEnglish": "Swadinota Shobdoti Amar Shohid Babar Somartok",
        "authorNameEnglish": "Sheikh Muslima Moon",
        "publisherNameEnglish": "Agamee Prokashoni",
        "primaryCategoryNameEnglish": "Poem- Bangla ",
        "listPrice": 160,
        "discount": 25,
        "sellPrice": 120,
        "image": "https://ds.rokomari.store/rokomari110/ProductNew20190903/260X372/5f827c528_195890.jpg",
        "status": "AVAILABLE",
        "averageRating": 0.0,
        "ratingCount": 0,
        "reviewCount": 0,
        "productType": "book",
        "link": "https://www.rokomari.com/book/195890",
        "inStock": true,
        "productOrderType": "NORMAL",
        "quantity": 4,
    },
    {
        "id": 195887,
        "nameEnglish": "Jiboner Rong",
        "authorNameEnglish": "Moslem Uddin Sagor",
        "publisherNameEnglish": "Agamee Prokashoni",
        "primaryCategoryNameEnglish": "Contemporary Novel  ",
        "listPrice": 160,
        "discount": 25,
        "sellPrice": 120,
        "image": "https://ds.rokomari.store/rokomari110/ProductNew20190903/260X372/29e59fbf4_195887.jpg",
        "status": "AVAILABLE",
        "averageRating": 5.0,
        "ratingCount": 1,
        "reviewCount": 1,
        "productType": "book",
        "link": "https://www.rokomari.com/book/195887",
        "inStock": true,
        "productOrderType": "NORMAL",
        "quantity": 7,
    },
    {
        "id": 194650,
        "nameEnglish": "Apotti sotteo",
        "authorNameEnglish": "Al Masum",
        "publisherNameEnglish": "Agamee Prokashoni",
        "primaryCategoryNameEnglish": "Rhymes",
        "listPrice": 250,
        "discount": 25,
        "sellPrice": 188,
        "image": "https://ds.rokomari.store/rokomari110/ProductNew20190903/260X372/727e63207_194650.jpg",
        "status": "AVAILABLE",
        "averageRating": 3.33,
        "ratingCount": 3,
        "reviewCount": 2,
        "productType": "book",
        "link": "https://www.rokomari.com/book/194650",
        "inStock": true,
        "productOrderType": "NORMAL",
        "quantity": 7,
    },
    {
        "id": 194084,
        "nameEnglish": "Proshasoner Ontorale",
        "authorNameEnglish": "Dr. Mohammad Amin",
        "publisherNameEnglish": "Agamee Prokashoni",
        "primaryCategoryNameEnglish": "Workplace Memories and Experience ",
        "listPrice": 500,
        "discount": 25,
        "sellPrice": 375,
        "image": "https://ds.rokomari.store/rokomari110/ProductNew20190903/260X372/d41cf9137_194084.jpg",
        "status": "AVAILABLE",
        "averageRating": 4.43,
        "ratingCount": 7,
        "reviewCount": 4,
        "productType": "book",
        "link": "https://www.rokomari.com/book/194084",
        "inStock": true,
        "productOrderType": "NORMAL",
        "quantity": 3,
    }
];

export default productLists;
